marcosschroh/dataclasses-avroschema

- README.md
- dataclasses_avroschema/fields.py
- tests/fields/consts.py
- tests/schemas/test_fastavro_paser_schema_.py
Optional types are a special case of Union types (union with NoneType),
so this just requires proper handling of NoneType fields.
> Support typing.Optional

- dataclasses_avroschema/fields.py
- dataclasses_avroschema/schema_definition.py
- tests/conftest.py
- tests/fields/test_BaseField.py
- tests/schemas/avro/user_with_field_metadata.avsc
- tests/schemas/conftest.py
- tests/schemas/test_fastavro_paser_schema_.py
- tests/schemas/test_schema.py
This PR implements the ability to store the `metadata` dict defined on a `dataclasses.dataclass` field. The use case is that we use custom field-level attributes to classify our data, e.g.:
```json
fields = [
{
"type": "string",
"name": "customer_name",
"classification": "sensitive"
},
{
"type": "string",
"name": "reason_of_call",
"classification": "non-sensitive"
}
]
```
Ultimately, this will allow the above to be produced from defining dataclasses which have the `metadata` field property defined, e.g.:
```python
import dataclasses
@dataclasses.dataclass
class Call:
customer_name: str = dataclasses.field(metadata={'classification': 'sensitive'})
reason_of_call: str = dataclasses.field(metadata={'classification': 'non-sensitive'}
```
> Allow Field to store dataclass.field.metadata

- dataclasses_avroschema/fields.py
- tests/fields/test_logical_types.py
- tests/schemas/avro/user_one_address_with_none_default.avsc
- tests/schemas/conftest.py
- tests/schemas/test_faust_schema.py
I choose the less intrusive approach.
But maybe it would be smarter to deal with the fields nullability in a more global way in `BaseField.render`. Where the default value is also managed.
something like : 
```python
def render(self) -> OrderedDict:
final_avro_type = self.get_avro_type()
if self.default is not dataclasses.MISSING:
if self.default is not None:
final_avro_type = [self.avro_type, NULL]
final_avro_type = [NULL, self.avro_type]
template = OrderedDict([("name", self.name), ("type", final_avro_type)] + self.get_metadata())
default = self.get_default_value()
if default is not None:
template["default"] = default
return template
```
> Deal with None and MISSING on LogicalTypeField and RecordField

- docs/fields_specification.md
This PR adds missing documentation for how to add custom field-level attr relating to feature https://github.com/marcosschroh/dataclasses-avroschema/pull/27. It also address a question raised in a recent issue https://github.com/marcosschroh/dataclasses-avroschema/issues/50.
> Add custom field attr documentation

- README.md
- dataclasses_avroschema/fields.py
- docs/index.md
- docs/primitive_types.md
- tests/fields/consts.py
- tests/schemas/avro/union_type.avsc
- tests/schemas/avro/user.avsc
- tests/schemas/avro/user_advance.avsc
- tests/schemas/avro/user_advance_with_defaults.avsc
- tests/schemas/avro/user_extra_avro_attributes.avsc
- tests/schemas/avro/user_many_address.avsc
- tests/schemas/avro/user_many_address_map.avsc
- tests/schemas/avro/user_one_address.avsc
- tests/schemas/avro/user_one_address_with_none_default.avsc
- tests/schemas/avro/user_self_reference_one_to_many.avsc
- tests/schemas/avro/user_self_reference_one_to_many_map.avsc
- tests/schemas/avro/user_self_reference_one_to_one.avsc
- tests/schemas/avro/user_v2.avsc
- tests/schemas/avro/user_with_field_metadata.avsc
... and Avro type for Python float to double.
Reasoning:
- "Integers have unlimited precision." [[1]](https://docs.python.org/3.4/library/stdtypes.html#typesnumeric)
- "Floating point numbers are usually implemented using double in C;" [[1]](https://docs.python.org/3.4/library/stdtypes.html#typesnumeric) and "almost all platforms map Python floats to IEEE-754 “double precision”." [[2]](https://docs.python.org/3/tutorial/floatingpoint.html#representation-error)
> Changed Avro type for Python int to long

- .gitignore
- dataclasses_avroschema/fields.py
- dataclasses_avroschema/serialization.py
- dataclasses_avroschema/types.py
- dataclasses_avroschema/utils.py
- docs/fields_specification.md
- docs/logical_types.md
- tests/fake/test_fake.py
- tests/fields/test_logical_types.py
- tests/schemas/avro/decimal.avsc
- tests/schemas/conftest.py
- tests/schemas/test_schema_with_logical_types.py
- tests/serialization/test_logical_types_serialization.py
Added in functionality for Decimal logical data types based of Python's decimal.Decimal class, added in fields and types.
Added in types and fields definitions for Decimal. Added in tests for fields and updated documentation. decimal.Decimal types can be declared in two ways:
```
class Example(AvroModel):
implicit: decimal.Decimal = decimal.Decimal('3.14')  # scale = 2, precision = 3, inherit from default
explicit: decimal.Decimal = types.Decimal(scale=2, precision=3, [default=decimal.Decimal('3.14'])
```
> Add support for decimal logical type

- .travis.yml
- dataclasses_avroschema/fields.py
- scripts/test
The test `tests/fields/test_complex_types.py::test_invalid_type_container_field` has been failing in Python 3.9.
This was caused by the refactor of `typing._GenericAlias`. This **PR** fixes this issue.
Additionally:
- all supported Python versions have been added to the Travis CI build. 
- the `mypy` job has been allowed to fail, as there is some issue with stubs for the **pytz** library.
> Fix GenericAlias test in Python 3.9. Add Python 3.8 and 3.9 in the CI build. Allow failure for the mypy job.

- dataclasses_avroschema/schema_definition.py
- dataclasses_avroschema/schema_generator.py
- dataclasses_avroschema/serialization.py
- dataclasses_avroschema/utils.py
- docs/complex_types.md
- docs/serialization.md
- tests/serialization/test_serialization.py
Currently, it's not possible to deserialize records encoded with a different, but compatible schema. This **PR** introduces an optional `writer_schema` argument to `AvroModel.deserialize`. This corresponds directly to the underlying **fastavro** `schema_less_reader` that executes the deserialization.
Additionally, this **PR** introduces a possibility to customize the `name` attribute in the generated Avro schema.
> Add `schema_name` attribute to `SchemaMetadata`. Add optional `writer_schema` in deserialization.

- dataclasses_avroschema/fields.py
- dataclasses_avroschema/schema_generator.py
- dataclasses_avroschema/types.py
This PR introduces some improvements of type annotations in the `AvroModel` class.
Most importantly, `deserialize` and `fake` methods, which now have correct and generic return types.
> Improve type annotations. 

- dataclasses_avroschema/fields.py
This must have been left in by mistake, but makes using this library very noisy
> Remove print statement

- .github/workflows/python-package.yml
- dataclasses_avroschema/case.py
- dataclasses_avroschema/schema_generator.py
- docs/case.md
- requirements.txt
- setup.py
- tests/case/test_case_records.py
- tests/schemas/test_fastavro_paser_schema.py
- tests/schemas/test_schema_with_logical_types.py
- tests/serialization/test_primitive_types_serialization.py
Available cases:
```python
CAMELCASE = "camelcase"
CAPITALCASE = "capitalcase"
CONSTCASE = "constcase"
LOWERCASE = "lowercase"
PASCALCASE = "pascalcase"
PATHCASE = "PATHCASE"
SNAKECASE = "snakecase"
SPINALCASE = "spinalcase"
TRIMCASE = "trimcase"
UPPERCASE = "uppercase"
ALPHANUMCASE = "alphanumcase"
```
Usage:
```python
import dataclasses
import typing
from dataclasses_avroschema import AvroModel, types, case
class UserAdvance(AvroModel):
name: str
age: int
pets: typing.List[str]
accounts: typing.Dict[str, int]
has_car: bool = False
favorite_colors: types.Enum = types.Enum(["BLUE", "YELLOW", "GREEN"])
country: str = "Argentina"
address: str = None
md5: types.Fixed = types.Fixed(16)
class Meta:
schema_doc = False
UserAdvance.avro_schema(case_type=case.PASCALCASE)
>>> '{"type": "record", …
```
> feat: case schemas

- dataclasses_avroschema/fields.py
- tests/fields/consts.py
```python
class MyModel(AvroModel):
my_dict: dict[str, Any]
my_list: list[int]
my_tuple: tuple[str]
```
Would previously fail
> fix: new style type annotations don't work for containers and maps

- dataclasses_avroschema/model_generator/generator.py
- docs/model_generator.md
- tests/model_generator/conftest.py
- tests/model_generator/test_model_generator.py
The new `render_module` method generates a Python module containing classes from one or more schemas (as opposed to `render` that accepts only one schema).
Generating a single module from multiple schemas is useful for example to group schemas that belong to the same namespace.
> Generate a Python module from multiple schemas

- dataclasses_avroschema/model_generator/avro_to_python_utils.py
- dataclasses_avroschema/model_generator/base_class.py
- dataclasses_avroschema/model_generator/generator.py
- docs/model_generator.md
- tests/model_generator/test_model_pydantic_generator.py
This PR updates pydantic model generation to use `pydantic.UUID4` instead of `uuid.uuid4`. The latter crashes pydantic. 🙃 Thank you for the fantastic library!
> fix: use pydantic UUID4 when generating pydantic models.

- dataclasses_avroschema/avrodantic.py
This PR addresses https://github.com/marcosschroh/dataclasses-avroschema/issues/299
Fixing type errors in method type annotations for AvroBaseModel in avrodantic.py.
> fix incorrect type annotations in avrodantic.py

- dataclasses_avroschema/fields/fields.py
- dataclasses_avroschema/fields/mapper.py
- dataclasses_avroschema/fields/pydantic_fields.py
- docs/pydantic.md
- tests/fake/const.py
- tests/fields/consts.py
- tests/model_generator/conftest.py
- tests/model_generator/test_model_pydantic_generator.py
- tests/serialization/test_pydantic_fields.py
Add pydantic `conint()` dynamic type support to allow schemas to use custom value constraints:
```
class ConstraintType(AvroBaseModel):
value: int = Field(gt=0)
```
This is initial PR to start discussion/approach - support for floats will come soon.
> feat: support pydantic constrained int fields

- dataclasses_avroschema/fields/fields.py
- dataclasses_avroschema/schema_definition.py
- tests/fields/test_BaseField.py
> fix: record fields avro schema creation (#382)

- dataclasses_avroschema/fields/fields.py
- dataclasses_avroschema/fields/mapper.py
- tests/fields/consts.py
- tests/fields/test_complex_types.py
- tests/fields/test_primitive_types.py
Resolves #424.
While working on the fix, I noticed some typos and minor issues:
- `readme.md` - To run tests locally, one should run `poetry install --all-extras`. Otherwise, tests will fail because `pydantic` is not installed.
- Common typo I**N**MUTABLE. Present in definitions in `dataclasses_avroschema/fields/mapper.py` and `tests/fields/test_primitive_types.py`.
- `tests/fields/consts.py` - tuple `PRIMITIVE_TYPES_AND_DEFAULTS` has member with `Annotated[bool, "boolen"]`. `a` is missing.
Should/may I also fix these problems?
> Resolve issues with raw `None` annotation

- dataclasses_avroschema/fields/fields.py
- tests/schemas/test_pydantic.py
Support for the `Literal` type added in #435 was missing a `fake()` definition. Added a simple one to pick a random input arg, and also added usage in the pydantic tests which would catch it.
> fix: add fake() support to Literal field type

- dataclasses_avroschema/faker.py
Closes #485; see there for details of why this is needed. (TLDR: `\.` is an invalid escape sequence.)
> Fix syntax warning in FakeStub docstring

- dataclasses_avroschema/schema_generator.py
Annotations for `*args`, `**kwargs` indicate the type of the values, not the structure Python passes back. See [PEP 484](https://peps.python.org/pep-0484/) for full details, but the relevant part is this:
> [...] the annotation here denotes the type of the individual argument values, not of the tuple/dict that you receive as the special argument value `args` or `kwds`.
A screenshot from PyCharm with an example:
> Fix kwarg typing in AvroModel

- poetry.lock
- pyproject.toml
Ref from this issue https://github.com/ixmatus/inflector/issues/15, removes syntax warnings for python3.12
> fix: bump inflector version for python3.12 support

- poetry.lock
- pyproject.toml
This is a fix for the following bug. typing-extensions  is now installed when using Python > 3.8
Describe the bug
typing extensions is not a required dependency when using Python > 3.8. So when using Python > 3.8 an import error is raised.
To Reproduce
Install dataclasses-avroschema using Python > 3.8. Make sure no other package is installing typing-extensions. Import error will be raised when trying to use AvroModel because of the following import: from typing_extensions import get_args.
Expected behavior
No import error.
Fix by updating [pyproject.toml](https://github.com/marcosschroh/dataclasses-avroschema/blob/master/pyproject.toml), remove python version requirement from typing-extensions.
> fix: install typing-extensions when using Python > 3.8. Closes #540

- dataclasses_avroschema/fields/fields.py
- dataclasses_avroschema/model_generator/lang/python/base.py
- dataclasses_avroschema/utils.py
- tests/model_generator/conftest.py
- tests/model_generator/test_model_generator.py
- tests/model_generator/test_model_pydantic_generator.py
Fixes https://github.com/marcosschroh/dataclasses-avroschema/issues/693 https://github.com/marcosschroh/dataclasses-avroschema/issues/692
This change fixed incorrect case rendering of fields inside a record which has the same record type and uses a reference of the type to determine the type of the field. Since the field name is converted to Pascal case for Record types, the reference type name should also be Pascal cased.
The Enum class rendering has a similar issue where the default value of the enum field does not contain the Pascal case of the Enum class.
> Fix: Fix incorrect casing when rendering fields and enums 

- dataclasses_avroschema/fields/base.py
- tests/schemas/avro/user_advance_with_duplicate_field_names.avsc
During avro_schema_to_python() call if two fields in different child fields of a class has same type and name, reuse the rendered field in the schema instead of re-rendering.
Fixes https://github.com/marcosschroh/dataclasses-avroschema/issues/709
Added a new round trip test with the nested fields in schema.
> fix: Always reuse the rendered type when type is same

- dataclasses_avroschema/model_generator/lang/python/base.py
- tests/model_generator/conftest.py
- tests/model_generator/test_model_generator.py
Original issue described in: https://github.com/marcosschroh/dataclasses-avroschema/issues/726 
Included a `logicalType` key check in `BaseGenerator.parse_logical_type` that does not break any of the existing model generations. But does enable the generation of a model for a schema with `logicalType` and `type` not defined under a `type` key (as described in the issue).
Note that my linter has updated some of the indentations in the code.
> fix: Implemented nested logicalType check

- dataclasses_avroschema/fields/field_utils.py
- dataclasses_avroschema/fields/fields.py
- dataclasses_avroschema/fields/mapper.py
- dataclasses_avroschema/model_generator/lang/python/avro_to_python_utils.py
- dataclasses_avroschema/model_generator/lang/python/templates.py
- dataclasses_avroschema/serialization.py
- docs/logical_types.md
- tests/fake/test_fake.py
- tests/fake/test_fake_pydantic.py
- tests/fake/test_fake_pydantic_v1.py
- tests/fields/test_logical_types.py
- tests/model_generator/conftest.py
- tests/model_generator/test_model_generator.py
- tests/model_generator/test_model_pydantic_generator.py
- tests/schemas/avro/logical_types.avsc
- tests/schemas/avro/logical_types_pydantic.avsc
- tests/schemas/avro/union_type.avsc
- tests/schemas/pydantic/test_pydantic.py
- tests/schemas/pydantic/test_pydantic_v1.py
- tests/schemas/test_fastavro_paser_schema.py
- tests/schemas/test_faust.py
- tests/schemas/test_roundtrip.py
- tests/schemas/test_schema_with_complex_types.py
- tests/schemas/test_schema_with_logical_types.py
- tests/serialization/test_logical_types_serialization.py
Serialize and deserialize Python `datetime.timedelta` fields to/from an Avro `double` number of seconds. 
This implements the `timedelta` serialization discussed in [this PR](https://github.com/marcosschroh/dataclasses-avroschema/pull/785). One difference from the solution discussed in that PR is that this uses `fastavro`'s [Custom Logical Types](https://fastavro.readthedocs.io/en/latest/logical_types.html#custom-logical-types) functionality, instead of doing the conversion in `standardize_custom_type`.
> feat: support timedelta serialization to `double` seconds

- .github/workflows/tests.yaml
- dataclasses_avroschema/utils.py
- pyproject.toml
In Python 3.13, the `typing.Annotated` type was changed to no longer support `isinstance` or `issubclass`. Replace the `is_annotated` implementation with code from Pydantic that checks to see if the origin of the type matches the `Annotated` type exported from either `typing` or `typing_extensions`.
Add Python 3.13 to the CI test matrix and to the library classifiers.
Fixes #816
> fix: support Python 3.13 in is_annotated

- docs/pydantic.md
The custom field-level documentation, when using Pydantic, references the exact instructions as if you were using data classes, but this doesn't work, as Pydantic doesn't have a `metadata` key in its `Field` function.
After some debugging, I found that you must use the `json_schema_extra` parameter in `Field,` passing a dictionary whose main key is `metadata,` with the object containing the field-level metadata you want to add.
[This is the `parser.py` reference to `json_schema_extra`](https://github.com/marcosschroh/dataclasses-avroschema/blob/master/dataclasses_avroschema/pydantic/parser.py#L32)
I tested this with the latest Pydantic version, and it works. I am unsure about Pydantic's v1, so this PR only addresses the latest Pydantic documentation.
I am happy to update the documentation …
> Fixes the Pydantic's custom field-level attributes docs

- dataclasses_avroschema/model_generator/lang/python/base.py
- tests/model_generator/conftest.py
- tests/model_generator/test_model_pydantic_generator.py
We now append an "_" to any fields that are Python keywords in order to still generate valid Python code.
> fix(ModelGenerator): Rename fields named after Python keywords. Closes #812
